server:
  port: 8801

spring:
  application:
    name: order-service
  rabbitmq: #消息队列
    host: 192.168.1.106
    username: guest
    password: guest
    port: 5672
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order_system?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    #连接池配置：
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5   # 数据库连接池的最小维持连接数
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  #redis配置
  redis:
    host: 127.0.0.1   #redis配置id
    port: 6379
    password: 123456
    #采用lettuce方式连接
    lettuce:
      shutdown-timeout: 100s # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30s # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #  type-aliases-package: com.qtu.entity
  configuration:
    map-underscore-to-camel-case: true

#日志配置
logging:
  level:
    com.qtu.user_service: debug

#雪花算法
keyGenerator:
  snowflake:
    workerId: 20 #工作机器进程ID，每个实例都要设置不同的值，范围：0-1023
    datacenterId: 20 #数据中心ID












eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/

###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

###开启Hystrix断路器
feign:
  hystrix:
    enabled: true
###配置请求超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000